upReal\ProductBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: upReal\ProductBundle\Entity\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '30'
        ean:
            type: string
            length: '30'
        picture:
            type: string
            length: '45'
        brand:
            type: string
            length: '30'
        uploadDate:
            type: datetime
            column: upload_date
    lifecycleCallbacks: {  }
