<?php

namespace upReal\UserBundle\Entity;

/**
 * KarmaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KarmaRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllByIdUser($id_user)
    {
	    $stmt = $this->getEntityManager()->getConnection()
	    ->prepare("SELECT *
	    	FROM upreal.karma 
	    	WHERE id_user = $id_user 
	    	");
	    $stmt->execute();
	    return $stmt->fetchAll();
    }
}
