<?php

namespace upReal\UserBundle\Entity;

/**
 * LoyaltyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoyaltyRepository extends \Doctrine\ORM\EntityRepository
{
}
