<?php

namespace upReal\UserBundle\Entity;

/**
 * PossessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PossessRepository extends \Doctrine\ORM\EntityRepository
{
	public function findMine($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p 
                FROM URUserBundle:Possess p
                WHERE p.idUser = '. $id . '')
            ->getResult();
    }
}
