<?php

namespace upReal\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findAll()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM URUserBundle:User p'
            )
            ->getResult();
    }
}
