<?php

namespace upReal\UserBundle\Entity;

/**
 * UserSellRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSellRepository extends \Doctrine\ORM\EntityRepository
{
	public function findLasts($nb, $idUser)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p 
                FROM URUserBundle:UserSell p
                WHERE p.user = ' . $idUser . ' ORDER BY p.id DESC'
            )
            ->setMaxResults($nb)
            ->getResult();
    }

    public function findUsersForProduct($idProduct)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p 
                FROM URUserBundle:UserSell p
                WHERE p.product = ' . $idProduct . ' ORDER BY p.price ASC'
            )
            ->getResult();
    }
}
