<?php

namespace upReal\SearchBundle\Entity;

/**
 * IdentifyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdentifyRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllWithKeyword($keyword)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM URSearchBundle:Identify p
                WHERE p.keyword = '. $keyword
            )
            ->getResult();
    }

    public function findCategoryDistributionFor($name)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT k.name AS name, count(p) AS nb
                FROM URProductBundle:Product p
                JOIN URSearchBundle:Identify i WITH i.idProduct = p.id
                JOIN URSearchBundle:keyword k WITH i.idKeyword = k.id
                WHERE p.name LIKE \'%'. $name. '%\'
                GROUP BY i.idKeyword')
            ->getResult();
    }

	public function findAllWithNameLike($name)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM URProductBundle:Product p
                WHERE p.name LIKE \'%'. $name. '%\'')
            ->getResult();
    }
}
