<?php

namespace upReal\SearchBundle\Entity;

/**
 * KeywordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeywordRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAll()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p 
                FROM URSearchBundle:Keyword p'
            )
            ->getResult();
    }
}
