<?php

namespace upReal\CompanyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
	public function findAll()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p 
                FROM URCompanyBundle:Company p'
            )
            ->getResult();
    }

    public function addCompany(\upReal\CompanyBundle\Entity\Company $company)
    {
        $n = $company->getName();
        $w = $company->getWebsite();

	    $stmt = $this->getEntityManager()->getConnection()
	    ->prepare("INSERT INTO company (name, website)
	    	VALUES ('$n', '$w')
	    	");
	    $stmt->execute();
    }
}
