<?php

namespace upReal\RateBundle\Entity;

/**
 * RateInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RateInfoRepository extends \Doctrine\ORM\EntityRepository
{
	public function findLikeForUserTarget($idUser, $idTarget)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p, r 
                FROM URRateBundle:RateInfo p
                JOIN p.rate r
                WITH r.idUser = '. $idUser . '
                WHERE p.idTarget = '. $idTarget .' AND p.type = 2'
                )
            ->getResult();
    }

    public function findDislikeForUserTarget($idUser, $idTarget)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p, r 
                FROM URRateBundle:RateInfo p
                JOIN p.rate r
                WITH r.idUser = '. $idUser . '
                WHERE p.idTarget = '. $idTarget .' AND p.type = 3'
                )
            ->getResult();
    }

    public function findCommentsForTarget($idTarget)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p, r 
                FROM URRateBundle:RateInfo p
                JOIN p.rate r
                WHERE p.idTarget = '. $idTarget .' AND p.type = 1'
                )
            ->getResult();
    }
}
