#    ur_core.example:
#        class: upReal\CoreBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
parameters:
    ur_core.oauth_members.class: upReal\CoreBundle\Services\OAuthMembersService

services:
    my_oauth_members:
        class: %ur_core.oauth_members.class%