<?php

namespace upReal\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
	public function findAll()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p 
                FROM URProductBundle:Product p'
            )
            ->getResult();
    }

    public function findLasts($nb)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p 
                FROM URProductBundle:Product p
                ORDER BY p.uploadDate DESC'
            )
            ->setMaxResults($nb)
            ->getResult();
    }
}
