<?php

namespace upReal\ProductBundle\Entity;

/**
 * SpecificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecificationRepository extends \Doctrine\ORM\EntityRepository
{
	public function findFor($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p 
                FROM URProductBundle:Specification p
                WHERE p.product = ' . $id
            )
            ->getResult();
    }
}
