<?php

namespace upReal\StoreBundle\Entity;

/**
 * StoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAll()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p 
                FROM URStoreBundle:Store p'
            )
            ->getResult();
    }

	public function findAllWithDetails()
	{
		$stmt = $this->getEntityManager()->getConnection()
	    ->prepare("SELECT s.name, s.website, a.address, a.city, a.country, a.postal_code, c.name AS company
	    	FROM Store s
	    	JOIN Address a ON s.id_address = a.id
	    	JOIN Company c ON s.id_company = c.id
	    	");
	    $stmt->execute();
	}
}
