<?php

namespace upReal\StoreBundle\Entity;

/**
 * StoreSellRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreSellRepository extends \Doctrine\ORM\EntityRepository
{
	public function findLasts($nb, $idStore)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p 
                FROM URStoreBundle:StoreSell p
                WHERE p.store = ' . $idStore . ' ORDER BY p.id DESC'
            )
            ->setMaxResults($nb)
            ->getResult();
    }

    public function findStoresForProduct($idProduct)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p 
                FROM URStoreBundle:StoreSell p
                WHERE p.product = ' . $idProduct . ' ORDER BY p.price ASC'
            )
            ->getResult();
    }
}
